[package]
name = "gitfetch"
version = "0.1.0"
edition = "2021"

[dependencies]
console = "0.15.8"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.132"
tokio = { version = "1", features = ["full"] }
